### ISSUE TITLE
TapirTypes

### ISSUE THREAD

**Issue by stelleg** [wsmoses/Tapir-Clang#3]
It looks like `include/clang/Basic/LangOptions.h` depends on `llvm/Transforms/Tapir/TapirTypes.h`, which doesn't exist in the current `Parallel-IR` master. Not seeing any obvious workarounds. Is there a branch that it exists in?

Thanks,
George

**Comment by stelleg** [comment]
Ah, I see now that it's in the omp branch, I'll try that.

**Comment by wsmoses** [comment]
Yeah it's waiting for merge into master once the CI passes.

**Comment by wsmoses** [comment]
OpenMP branch now merged into Parallel-IR master, closing
