### ISSUE TITLE
clang: error: unable to execute command: Segmentation fault

### ISSUE THREAD

**Issue by JacksonKearl** [wsmoses/Tapir-Clang#5]
The statement:
`cilk_for(int i = j; i < i + 10; i++)`
(where the second i in the conditional has be erroneously substituted for j) causes a Segfault when compiling. Should probably not Segfualt?

**Comment by neboat** [comment]
Thanks for the note.  I'll look into this.  I suspect we need to improve the front-end checks for cilk_for syntax.  Do you have a test case that we can compile and examine?

**Comment by wsmoses** [comment]
@JacksonKearl any thoughts on a test case which caused this? If not, will close.
